# permissions for end users to edit mutatingwebhooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mutatingwebhook-editor-role
rules:
- apiGroups:
  - core.giantswarm.io
  resources:
  - mutatingwebhooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.giantswarm.io
  resources:
  - mutatingwebhooks/status
  verbs:
  - get
