# permissions for end users to view servicecertificatetemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: servicecertificatetemplate-viewer-role
rules:
- apiGroups:
  - core.giantswarm.io
  resources:
  - servicecertificatetemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.giantswarm.io
  resources:
  - servicecertificatetemplates/status
  verbs:
  - get
