//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	admissionregistrationv1 "k8s.io/api/admissionregistration/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdmissionWebhookTemplateSpec) DeepCopyInto(out *AdmissionWebhookTemplateSpec) {
	*out = *in
	in.Handler.DeepCopyInto(&out.Handler)
	if in.ObjectSelector != nil {
		in, out := &in.ObjectSelector, &out.ObjectSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.IgnoreErrors != nil {
		in, out := &in.IgnoreErrors, &out.IgnoreErrors
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdmissionWebhookTemplateSpec.
func (in *AdmissionWebhookTemplateSpec) DeepCopy() *AdmissionWebhookTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(AdmissionWebhookTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in Conditions) DeepCopyInto(out *Conditions) {
	{
		in := &in
		*out = make(Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Conditions.
func (in Conditions) DeepCopy() Conditions {
	if in == nil {
		return nil
	}
	out := new(Conditions)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversionWebhookTemplate) DeepCopyInto(out *ConversionWebhookTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversionWebhookTemplate.
func (in *ConversionWebhookTemplate) DeepCopy() *ConversionWebhookTemplate {
	if in == nil {
		return nil
	}
	out := new(ConversionWebhookTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConversionWebhookTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversionWebhookTemplateList) DeepCopyInto(out *ConversionWebhookTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConversionWebhookTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversionWebhookTemplateList.
func (in *ConversionWebhookTemplateList) DeepCopy() *ConversionWebhookTemplateList {
	if in == nil {
		return nil
	}
	out := new(ConversionWebhookTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConversionWebhookTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConversionWebhookTemplateSpec) DeepCopyInto(out *ConversionWebhookTemplateSpec) {
	*out = *in
	in.Handler.DeepCopyInto(&out.Handler)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConversionWebhookTemplateSpec.
func (in *ConversionWebhookTemplateSpec) DeepCopy() *ConversionWebhookTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ConversionWebhookTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResourceDefinitionDeployment) DeepCopyInto(out *CustomResourceDefinitionDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResourceDefinitionDeployment.
func (in *CustomResourceDefinitionDeployment) DeepCopy() *CustomResourceDefinitionDeployment {
	if in == nil {
		return nil
	}
	out := new(CustomResourceDefinitionDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomResourceDefinitionDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResourceDefinitionDeploymentList) DeepCopyInto(out *CustomResourceDefinitionDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CustomResourceDefinitionDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResourceDefinitionDeploymentList.
func (in *CustomResourceDefinitionDeploymentList) DeepCopy() *CustomResourceDefinitionDeploymentList {
	if in == nil {
		return nil
	}
	out := new(CustomResourceDefinitionDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomResourceDefinitionDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResourceDefinitionDeploymentSpec) DeepCopyInto(out *CustomResourceDefinitionDeploymentSpec) {
	*out = *in
	in.Versions.DeepCopyInto(&out.Versions)
	out.Source = in.Source
	if in.MutatingWebhook != nil {
		in, out := &in.MutatingWebhook, &out.MutatingWebhook
		*out = new(CustomResourceDefinitionWebhookConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ValidatingWebhook != nil {
		in, out := &in.ValidatingWebhook, &out.ValidatingWebhook
		*out = new(CustomResourceDefinitionWebhookConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ConversionWebhook != nil {
		in, out := &in.ConversionWebhook, &out.ConversionWebhook
		*out = new(CustomResourceDefinitionWebhookConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResourceDefinitionDeploymentSpec.
func (in *CustomResourceDefinitionDeploymentSpec) DeepCopy() *CustomResourceDefinitionDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(CustomResourceDefinitionDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResourceDefinitionDeploymentStatus) DeepCopyInto(out *CustomResourceDefinitionDeploymentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResourceDefinitionDeploymentStatus.
func (in *CustomResourceDefinitionDeploymentStatus) DeepCopy() *CustomResourceDefinitionDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(CustomResourceDefinitionDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResourceDefinitionServedVersion) DeepCopyInto(out *CustomResourceDefinitionServedVersion) {
	*out = *in
	if in.Deprecated != nil {
		in, out := &in.Deprecated, &out.Deprecated
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResourceDefinitionServedVersion.
func (in *CustomResourceDefinitionServedVersion) DeepCopy() *CustomResourceDefinitionServedVersion {
	if in == nil {
		return nil
	}
	out := new(CustomResourceDefinitionServedVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResourceDefinitionSource) DeepCopyInto(out *CustomResourceDefinitionSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResourceDefinitionSource.
func (in *CustomResourceDefinitionSource) DeepCopy() *CustomResourceDefinitionSource {
	if in == nil {
		return nil
	}
	out := new(CustomResourceDefinitionSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResourceDefinitionVersionsConfig) DeepCopyInto(out *CustomResourceDefinitionVersionsConfig) {
	*out = *in
	if in.Served != nil {
		in, out := &in.Served, &out.Served
		*out = make([]CustomResourceDefinitionServedVersion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResourceDefinitionVersionsConfig.
func (in *CustomResourceDefinitionVersionsConfig) DeepCopy() *CustomResourceDefinitionVersionsConfig {
	if in == nil {
		return nil
	}
	out := new(CustomResourceDefinitionVersionsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResourceDefinitionWebhookConfig) DeepCopyInto(out *CustomResourceDefinitionWebhookConfig) {
	*out = *in
	in.TemplateRef.DeepCopyInto(&out.TemplateRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResourceDefinitionWebhookConfig.
func (in *CustomResourceDefinitionWebhookConfig) DeepCopy() *CustomResourceDefinitionWebhookConfig {
	if in == nil {
		return nil
	}
	out := new(CustomResourceDefinitionWebhookConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MutatingWebhookTemplate) DeepCopyInto(out *MutatingWebhookTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MutatingWebhookTemplate.
func (in *MutatingWebhookTemplate) DeepCopy() *MutatingWebhookTemplate {
	if in == nil {
		return nil
	}
	out := new(MutatingWebhookTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MutatingWebhookTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MutatingWebhookTemplateList) DeepCopyInto(out *MutatingWebhookTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MutatingWebhookTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MutatingWebhookTemplateList.
func (in *MutatingWebhookTemplateList) DeepCopy() *MutatingWebhookTemplateList {
	if in == nil {
		return nil
	}
	out := new(MutatingWebhookTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MutatingWebhookTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MutatingWebhookTemplateSpec) DeepCopyInto(out *MutatingWebhookTemplateSpec) {
	*out = *in
	in.AdmissionWebhookTemplateSpec.DeepCopyInto(&out.AdmissionWebhookTemplateSpec)
	if in.ReinvocationPolicy != nil {
		in, out := &in.ReinvocationPolicy, &out.ReinvocationPolicy
		*out = new(admissionregistrationv1.ReinvocationPolicyType)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MutatingWebhookTemplateSpec.
func (in *MutatingWebhookTemplateSpec) DeepCopy() *MutatingWebhookTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(MutatingWebhookTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceReference) DeepCopyInto(out *ServiceReference) {
	*out = *in
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.PathStyle != nil {
		in, out := &in.PathStyle, &out.PathStyle
		*out = new(WebhookPathStyle)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceReference.
func (in *ServiceReference) DeepCopy() *ServiceReference {
	if in == nil {
		return nil
	}
	out := new(ServiceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidatingWebhookTemplate) DeepCopyInto(out *ValidatingWebhookTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidatingWebhookTemplate.
func (in *ValidatingWebhookTemplate) DeepCopy() *ValidatingWebhookTemplate {
	if in == nil {
		return nil
	}
	out := new(ValidatingWebhookTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ValidatingWebhookTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidatingWebhookTemplateList) DeepCopyInto(out *ValidatingWebhookTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ValidatingWebhookTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidatingWebhookTemplateList.
func (in *ValidatingWebhookTemplateList) DeepCopy() *ValidatingWebhookTemplateList {
	if in == nil {
		return nil
	}
	out := new(ValidatingWebhookTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ValidatingWebhookTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValidatingWebhookTemplateSpec) DeepCopyInto(out *ValidatingWebhookTemplateSpec) {
	*out = *in
	in.AdmissionWebhookTemplateSpec.DeepCopyInto(&out.AdmissionWebhookTemplateSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValidatingWebhookTemplateSpec.
func (in *ValidatingWebhookTemplateSpec) DeepCopy() *ValidatingWebhookTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(ValidatingWebhookTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookHandlerConfig) DeepCopyInto(out *WebhookHandlerConfig) {
	*out = *in
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(ServiceReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookHandlerConfig.
func (in *WebhookHandlerConfig) DeepCopy() *WebhookHandlerConfig {
	if in == nil {
		return nil
	}
	out := new(WebhookHandlerConfig)
	in.DeepCopyInto(out)
	return out
}
